name: PR Review
 
on:
  pull_request:
    types: [opened, synchronize, reopened]
 
permissions:
  contents: read
  pull-requests: write
 
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: DhavanBhalodiya/CodeReviewerAgent@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          llm-provider: anthropic
          #anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # llm-model: claude-opus-4-8          # optional override
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}   # if using openai instead
 
